// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ItpdevelopmentTestProject.Models
{
    public partial class Project
    {
        public Project()
        {
            Task = new HashSet<Task>();
        }

        public Guid Id { get; set; }
        public string ProjectName { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual ICollection<Task> Task { get; set; }
    }
}