// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ItpdevelopmentTestProject.Models
{
    public partial class Task
    {
        public Task()
        {
            TaskComments = new HashSet<TaskComments>();
        }

        public Guid Id { get; set; }
        public string TaskName { get; set; }
        public Guid ProjectId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? CancelDate { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<TaskComments> TaskComments { get; set; }
    }
}